---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elastic
  template:
    metadata:
      labels:
        component: elastic
    spec:
      containers:
      - name: elastic
        image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.elastic.co/elasticsearch/elasticsearch:9.2.1
        ports:
        - name: http
          containerPort: 9200
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-server -Xss1024K -Xmx2G -Duser.timezone=Asia/Shanghai"
        - name: bootstrap.memory_lock
          value: 'true'
        - name: TAKE_FILE_OWNERSHIP
          value: 'true'  
        - name: xpack.security.autoconfiguration.enabled
          value: "false"
        - name: xpack.security.enabled
          value: "true"
        # - name: ELASTIC_PASSWORD
        #   value: "elastic@123"
        # - name: KIBANA_SYSTEM_PASSWORD
        #  value: "kibana@123" 
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: ELASTIC_PASSWORD
        - name: KIBANA_SYSTEM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: KIBANA_SYSTEM_PASSWORD
      volumes:
      - name: data
        persistentVolumeClaim:
            claimName: elasticsearch-pv-claim
